imports:
    - { resource: "@RechercheBundle/Resources/config/elastica.yml" }

services:
#    recherche.example:
#        class: RechercheBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]

