<?php

namespace PaieBundle\Repository;

/**
 * CotisationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CotisationRepository extends \Doctrine\ORM\EntityRepository
{

    public function countCotisationByUserId($id)
    {
        $query = $this->getEntityManager()
            ->createQuery('SELECT COUNT(p.id) FROM PaieBundle:Cotisation p WHERE p.salarie = :id')
            ->setParameter('id', $id);
        try {
            return $query->getSingleScalarResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return 0;
        }
    }
    
    public function removeAllCotisationByUserId($id) {
        $cotisations= $this->getAllCotisationByUserId($id);
        foreach ($cotisations as $cotisation)
        {
            $this->getEntityManager()->remove($cotisation);
        }
        $this->getEntityManager()->flush();
    }

    public function getAllCotisationByUserId($id) {
        $query = $this->getEntityManager()
            ->createQuery('SELECT p FROM PaieBundle:Cotisation p WHERE p.salarie = :id')
            ->setParameter('id', $id);
        return $query->getResult();
    }


}
