ccdn_forum_forum:
    form:
        type:
            board_create:
                class:   ForumBundle\Form\Type\Admin\Board\BoardCreateFormType
            board_update:
                class:   ForumBundle\Form\Type\Admin\Board\BoardUpdateFormType

    forum:
        admin:
            create:
                layout_template:      ForumBundle::base.html.twig
#                form_theme:           CCDNForumForumBundle:Common:Form/fields.html.twig
            delete:
                layout_template:      ForumBundle::base.html.twig
#                form_theme:           CCDNForumForumBundle:Common:Form/fields.html.twig
            edit:
                layout_template:      ForumBundle::base.html.twig
#                form_theme:           CCDNForumForumBundle:Common:Form/fields.html.twig
            list:
                layout_template:      ForumBundle::base.html.twig
    category:
        admin:
            create:
                layout_template:      ForumBundle::base.html.twig
#                form_theme:           CCDNForumForumBundle:Common:Form/fields.html.twig
            delete:
                layout_template:      ForumBundle::base.html.twig
#                form_theme:           CCDNForumForumBundle:Common:Form/fields.html.twig
            edit:
                layout_template:      ForumBundle::base.html.twig
#                form_theme:           CCDNForumForumBundle:Common:Form/fields.html.twig
            list:
                layout_template:      ForumBundle::base.html.twig
        user:
            last_post_datetime_format:  Y/m/d H:i
            index:
                layout_template:      ForumBundle::base.html.twig
            show:
                layout_template:      ForumBundle::base.html.twig
    board:
        admin:
            create:
                layout_template:      ForumBundle::base.html.twig
#                form_theme:           CCDNForumForumBundle:Common:Form/fields.html.twig
            delete:
                layout_template:      ForumBundle::base.html.twig
#               form_theme:           CCDNForumForumBundle:Common:Form/fields.html.twig
            edit:
                layout_template:      ForumBundle::base.html.twig
#                form_theme:           CCDNForumForumBundle:Common:Form/fields.html.twig
            list:
                layout_template:      ForumBundle::base.html.twig
        user:
            show:
                layout_template:      ForumBundle::base.html.twig
                topics_per_page:      50
                topic_title_truncate:  50
                first_post_datetime_format:  Y/m/d H:i
                last_post_datetime_format:  Y/m/d H:i
    topic:
        moderator:
            change_board:
                layout_template:      ForumBundle::base.html.twig
#                form_theme:           CCDNForumForumBundle:Common:Form/fields.html.twig
            delete:
                layout_template:      ForumBundle::base.html.twig
#                form_theme:           CCDNForumForumBundle:Common:Form/fields.html.twig
        user:
            flood_control:
                post_limit:           4
                block_for_minutes:    1
            show:
                layout_template:      CCDNForumForumBundle::base.html.twig
                posts_per_page:       20
                closed_datetime_format:  Y/m/d H:i
                deleted_datetime_format:  Y/m/d H:i
            create:
                layout_template:      ForumBundle::base.html.twig
#                form_theme:           CCDNForumForumBundle:Common:Form/fields.html.twig
            reply:
                layout_template:      ForumBundle::base.html.twig
#                form_theme:           CCDNForumForumBundle:Common:Form/fields.html.twig
    post:
        moderator:
            unlock:
                layout_template:      ForumBundle::base.html.twig
#                form_theme:           CCDNForumForumBundle:Common:Form/fields.html.twig
        user:
            show:
                layout_template:      ForumBundle::base.html.twig
            edit:
                layout_template:      ForumBundle::base.html.twig
#                form_theme:           CCDNForumForumBundle:Common:Form/fields.html.twig
            delete:
                layout_template:      ForumBundle::base.html.twig
#                form_theme:           CCDNForumForumBundle:Common:Form/fields.html.twig
            lock:
                enable:               true
                after_days:           7
    item_post:
        created_datetime_format:  Y/m/d H:i
        edited_datetime_format:   Y/m/d H:i
        locked_datetime_format:   Y/m/d H:i
        deleted_datetime_format:  Y/m/d H:i
    subscription:
        list:
            layout_template:      ForumBundle::base.html.twig
            topics_per_page:      50
            topic_title_truncate:  50
            first_post_datetime_format: Y/m/d H:i
            last_post_datetime_format:  Y/m/d H:i