
imports:
    - { resource: "@PaieBundle/Resources/config/default_cotisation.yml" }

services:
#    paie.example:
#        class: PaieBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
